import jsPDF from 'jspdf';

export interface JumpPDFData {
  title: string;
  summary?: string;
  content: string;
  createdAt: string;
}

export const generateJumpPDF = (jumpData: JumpPDFData): void => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 24;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  // Professional color palette matching website design
  const colors = {
    background: [255, 255, 255], // White background
    foreground: [10, 10, 10], // Nearly black text (--foreground: 0 0% 3.9%)
    muted: [115, 115, 115], // Muted text (--muted-foreground: 0 0% 45.1%)
    border: [229, 229, 229], // Border color (--border: 0 0% 89.8%)
    accent: [245, 245, 245], // Light gray accent (--accent: 0 0% 96.1%)
    primary: [23, 23, 23], // Primary dark (--primary: 0 0% 9%)
  } as const;

  // Helper function to add new page if needed
  const checkPageBreak = (neededHeight: number) => {
    if (yPosition + neededHeight > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin + 20; // Account for header on new pages
      addPageHeader();
    }
  };

  // Helper function to wrap text with better line spacing
  const wrapText = (text: string, maxWidth: number, fontSize: number) => {
    pdf.setFontSize(fontSize);
    return pdf.splitTextToSize(text, maxWidth);
  };

  // Add professional page header
  const addPageHeader = () => {
    // Subtle top border
    pdf.setDrawColor(...colors.border);
    pdf.setLineWidth(0.5);
    pdf.line(0, 15, pageWidth, 15);
    
    // JumpinAI logo text (top right)
    pdf.setTextColor(...colors.muted);
    pdf.setFontSize(9);
    pdf.setFont('helvetica', 'normal');
    pdf.text('Generated by JumpinAI', pageWidth - margin - 35, 12);
  };

  // Add main header
  addPageHeader();

  // Professional document title section
  pdf.setFillColor(...colors.accent);
  pdf.roundedRect(margin, yPosition, maxWidth, 50, 4, 4, 'F');
  
  // Add subtle border to title box
  pdf.setDrawColor(...colors.border);
  pdf.setLineWidth(0.5);
  pdf.roundedRect(margin, yPosition, maxWidth, 50, 4, 4, 'S');

  // Document title
  pdf.setTextColor(...colors.foreground);
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  const titleLines = wrapText(jumpData.title, maxWidth - 32, 20);
  const titleY = yPosition + 18 + (titleLines.length > 1 ? 0 : 4);
  pdf.text(titleLines, margin + 16, titleY);

  yPosition += 65;

  // Document metadata section
  const metaY = yPosition;
  
  // Creation date
  pdf.setTextColor(...colors.muted);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Created: ${new Date(jumpData.createdAt).toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })}`, margin, metaY);
  
  // AI Generated badge (right aligned)
  const badgeWidth = 85;
  const badgeX = pageWidth - margin - badgeWidth;
  pdf.setFillColor(...colors.accent);
  pdf.setDrawColor(...colors.border);
  pdf.roundedRect(badgeX, metaY - 8, badgeWidth, 16, 2, 2, 'FD');
  
  pdf.setTextColor(...colors.muted);
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'bold');
  pdf.text('🤖 AI GENERATED', badgeX + 8, metaY);
  
  yPosition += 35;

  // Process content - convert markdown to PDF
  const processContent = (content: string) => {
    const lines = content.split('\n');
    
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      
      if (!line) {
        yPosition += 5;
        continue;
      }

      // Headers - matching website typography
      if (line.startsWith('# ')) {
        checkPageBreak(30);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(18);
        pdf.setFont('helvetica', 'bold');
        const headerText = line.substring(2).trim();
        const headerLines = wrapText(headerText, maxWidth, 18);
        pdf.text(headerLines, margin, yPosition);
        yPosition += headerLines.length * 9 + 6;
        
        // Add subtle underline matching website style
        pdf.setDrawColor(...colors.border);
        pdf.setLineWidth(0.5);
        pdf.line(margin, yPosition, margin + maxWidth * 0.3, yPosition);
        yPosition += 12;
        
      } else if (line.startsWith('## ')) {
        checkPageBreak(25);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(15);
        pdf.setFont('helvetica', 'bold');
        const headerText = line.substring(3).trim();
        const headerLines = wrapText(headerText, maxWidth, 15);
        pdf.text(headerLines, margin, yPosition);
        yPosition += headerLines.length * 8 + 10;
        
      } else if (line.startsWith('### ')) {
        checkPageBreak(20);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(13);
        pdf.setFont('helvetica', 'bold');
        const headerText = line.substring(4).trim();
        const headerLines = wrapText(headerText, maxWidth, 13);
        pdf.text(headerLines, margin, yPosition);
        yPosition += headerLines.length * 7 + 8;
        
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        // Bullet points - matching website list styling
        checkPageBreak(18);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        
        // Modern bullet point (small filled circle)
        pdf.setFillColor(...colors.primary);
        pdf.circle(margin + 4, yPosition - 1.5, 1.2, 'F');
        
        const bulletText = line.substring(2).trim();
        const bulletLines = wrapText(bulletText, maxWidth - 16, 11);
        pdf.text(bulletLines, margin + 12, yPosition);
        yPosition += bulletLines.length * 6 + 4;
        
      } else if (line.match(/^\d+\. /)) {
        // Numbered lists
        checkPageBreak(18);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        
        const numberedLines = wrapText(line, maxWidth, 11);
        pdf.text(numberedLines, margin, yPosition);
        yPosition += numberedLines.length * 6 + 4;
        
      } else if (line.startsWith('**') && line.endsWith('**')) {
        // Bold text sections
        checkPageBreak(18);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        const boldText = line.substring(2, line.length - 2);
        const boldLines = wrapText(boldText, maxWidth, 11);
        pdf.text(boldLines, margin, yPosition);
        yPosition += boldLines.length * 6 + 8;
        
      } else {
        // Regular paragraph - matching website text styling
        checkPageBreak(18);
        pdf.setTextColor(...colors.foreground);
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        
        // Process inline formatting while preserving emphasis
        let processedLine = line;
        
        // Handle inline code with background highlight
        const codeMatches = processedLine.match(/`([^`]+)`/g);
        if (codeMatches) {
          // For now, just remove backticks and style differently
          processedLine = processedLine.replace(/`([^`]+)`/g, '$1');
        }
        
        // Remove markdown formatting for cleaner PDF text
        processedLine = processedLine.replace(/\*\*(.*?)\*\*/g, '$1');
        processedLine = processedLine.replace(/\*(.*?)\*/g, '$1');
        
        if (processedLine.trim()) {
          const paragraphLines = wrapText(processedLine, maxWidth, 11);
          pdf.text(paragraphLines, margin, yPosition);
          yPosition += paragraphLines.length * 6.5 + 10;
        }
      }
    }
  };

  processContent(jumpData.content);

  // Add professional footer to all pages
  const pageCount = pdf.internal.pages.length - 1;
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    
    // Footer separator line
    pdf.setDrawColor(...colors.border);
    pdf.setLineWidth(0.3);
    pdf.line(margin, pageHeight - 25, pageWidth - margin, pageHeight - 25);
    
    // Footer content
    pdf.setTextColor(...colors.muted);
    pdf.setFontSize(8);
    pdf.setFont('helvetica', 'normal');
    
    // Page number (right)
    pdf.text(`${i} / ${pageCount}`, pageWidth - margin - 20, pageHeight - 15);
    
    // Generated by text (left)
    pdf.text('Generated by JumpinAI', margin, pageHeight - 15);
    
    // Date generated (center)
    const currentDate = new Date().toLocaleDateString('en-US', { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric' 
    });
    const centerText = `Generated on ${currentDate}`;
    const centerX = (pageWidth - pdf.getTextWidth(centerText)) / 2;
    pdf.text(centerText, centerX, pageHeight - 15);
  }

  // Download the PDF with clean filename
  const cleanTitle = jumpData.title
    .replace(/[^a-zA-Z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .toLowerCase()
    .substring(0, 50); // Limit length
  
  const fileName = `${cleanTitle || 'jump-plan'}.pdf`;
  pdf.save(fileName);
};