import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download, Edit, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { formatAIText } from '@/utils/aiTextFormatter';

interface JumpPlanDisplayProps {
  planContent: string;
  structuredPlan?: any; // Optional structured data for enhanced display
  onEdit: () => void;
  onDownload: () => void;
}

export default function JumpPlanDisplay({ planContent, structuredPlan, onEdit, onDownload }: JumpPlanDisplayProps) {
  if (!planContent.trim()) {
    return null;
  }

  const enhancedContent = React.useMemo(() => formatAIText(planContent), [planContent]);

  return (
    <Card className="w-full bg-card border-border">
      <CardHeader className="pb-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-full bg-gradient-to-br from-primary/20 to-primary/10">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle className="text-xl">Your AI-Generated Jump Plan</CardTitle>
              <p className="text-sm text-muted-foreground mt-1">
                Your personalized transformation roadmap
              </p>
            </div>
          </div>
          <Badge variant="secondary" className="bg-primary/10 text-primary border-primary/20">
            Generated by AI
          </Badge>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onDownload}
            className="gap-2"
          >
            <Download className="h-4 w-4" />
            Download Plan
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onEdit}
            className="gap-2"
          >
            <Edit className="h-4 w-4" />
            Refine with Chat
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {structuredPlan ? (
          // Enhanced structured display when structured data is available
          <div className="space-y-6">
            {/* Title */}
            {structuredPlan.title && (
              <div className="text-center pb-6 border-b border-border">
                <h1 className="text-3xl font-bold gradient-text-primary mb-2">{structuredPlan.title}</h1>
              </div>
            )}

            {/* Executive Summary */}
            {structuredPlan.executive_summary && (
              <div className="bg-gradient-to-r from-primary/5 to-primary/10 rounded-lg p-6 border border-primary/20">
                <h2 className="text-xl font-semibold text-primary mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-primary"></div>
                  Executive Summary
                </h2>
                <p className="text-muted-foreground leading-relaxed">{structuredPlan.executive_summary}</p>
              </div>
            )}

            {/* Current State Analysis */}
            {structuredPlan.current_state_analysis && (
              <div className="bg-muted/30 rounded-lg p-6 border border-border">
                <h2 className="text-xl font-semibold text-foreground mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-secondary"></div>
                  Current State Analysis
                </h2>
                <p className="text-muted-foreground leading-relaxed">{structuredPlan.current_state_analysis}</p>
              </div>
            )}

            {/* Transformation Goal */}
            {structuredPlan.transformation_goal && (
              <div className="bg-gradient-to-r from-secondary/5 to-secondary/10 rounded-lg p-6 border border-secondary/20">
                <h2 className="text-xl font-semibold text-secondary mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-secondary"></div>
                  Transformation Goal
                </h2>
                <p className="text-muted-foreground leading-relaxed">{structuredPlan.transformation_goal}</p>
              </div>
            )}

            {/* Phases */}
            {structuredPlan.phases && Array.isArray(structuredPlan.phases) && (
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-primary"></div>
                  The Jump Plan
                </h2>
                {structuredPlan.phases.map((phase: any, index: number) => (
                  <div key={index} className="bg-card rounded-lg border border-border p-6 shadow-lg">
                    <div className="flex items-start justify-between mb-4">
                      <h3 className="text-xl font-semibold text-primary">
                        Phase {phase.phase_number || index + 1}: {phase.title}
                      </h3>
                      {phase.timeline && (
                        <span className="text-sm bg-primary/10 text-primary px-3 py-1 rounded-full">
                          {phase.timeline}
                        </span>
                      )}
                    </div>
                    {phase.description && (
                      <p className="text-muted-foreground mb-4 leading-relaxed">{phase.description}</p>
                    )}
                    
                    <div className="grid md:grid-cols-3 gap-4">
                      {phase.key_actions && Array.isArray(phase.key_actions) && (
                        <div>
                          <h4 className="font-medium text-foreground mb-2">Key Actions</h4>
                          <ul className="space-y-1">
                            {phase.key_actions.map((action: string, actionIndex: number) => (
                              <li key={actionIndex} className="text-sm text-muted-foreground flex items-start gap-2">
                                <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 flex-shrink-0"></div>
                                {action}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      
                      {phase.deliverables && Array.isArray(phase.deliverables) && (
                        <div>
                          <h4 className="font-medium text-foreground mb-2">Deliverables</h4>
                          <ul className="space-y-1">
                            {phase.deliverables.map((deliverable: string, delIndex: number) => (
                              <li key={delIndex} className="text-sm text-muted-foreground flex items-start gap-2">
                                <div className="w-1.5 h-1.5 rounded-full bg-secondary mt-2 flex-shrink-0"></div>
                                {deliverable}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      
                      {phase.success_criteria && Array.isArray(phase.success_criteria) && (
                        <div>
                          <h4 className="font-medium text-foreground mb-2">Success Criteria</h4>
                          <ul className="space-y-1">
                            {phase.success_criteria.map((criteria: string, critIndex: number) => (
                              <li key={critIndex} className="text-sm text-muted-foreground flex items-start gap-2">
                                <div className="w-1.5 h-1.5 rounded-full bg-green-500 mt-2 flex-shrink-0"></div>
                                {criteria}
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Tools, Metrics, and Challenges Grid */}
            <div className="grid md:grid-cols-2 gap-6">
              {/* Recommended Tools */}
              {structuredPlan.recommended_tools && Array.isArray(structuredPlan.recommended_tools) && (
                <div className="bg-blue-50/50 dark:bg-blue-950/20 rounded-lg p-6 border border-blue-200/50">
                  <h2 className="text-xl font-semibold text-blue-700 dark:text-blue-400 mb-4 flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-blue-500"></div>
                    Recommended Tools
                  </h2>
                  <ul className="space-y-2">
                    {structuredPlan.recommended_tools.map((tool: string, index: number) => (
                      <li key={index} className="text-sm text-muted-foreground flex items-center gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-blue-500"></div>
                        {tool}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Success Metrics */}
              {structuredPlan.success_metrics && Array.isArray(structuredPlan.success_metrics) && (
                <div className="bg-green-50/50 dark:bg-green-950/20 rounded-lg p-6 border border-green-200/50">
                  <h2 className="text-xl font-semibold text-green-700 dark:text-green-400 mb-4 flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-green-500"></div>
                    Success Metrics
                  </h2>
                  <ul className="space-y-2">
                    {structuredPlan.success_metrics.map((metric: string, index: number) => (
                      <li key={index} className="text-sm text-muted-foreground flex items-center gap-2">
                        <div className="w-1.5 h-1.5 rounded-full bg-green-500"></div>
                        {metric}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Challenges and Next Steps Grid */}
            <div className="grid md:grid-cols-2 gap-6">
              {/* Potential Challenges */}
              {structuredPlan.potential_challenges && Array.isArray(structuredPlan.potential_challenges) && (
                <div className="bg-orange-50/50 dark:bg-orange-950/20 rounded-lg p-6 border border-orange-200/50">
                  <h2 className="text-xl font-semibold text-orange-700 dark:text-orange-400 mb-4 flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                    Potential Challenges
                  </h2>
                  <div className="space-y-3">
                    {structuredPlan.potential_challenges.map((challenge: string, index: number) => (
                      <div key={index} className="text-sm">
                        <p className="text-muted-foreground mb-1">
                          <strong>Challenge:</strong> {challenge}
                        </p>
                        {structuredPlan.mitigation_strategies && structuredPlan.mitigation_strategies[index] && (
                          <p className="text-muted-foreground text-xs">
                            <strong>Solution:</strong> {structuredPlan.mitigation_strategies[index]}
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Next Immediate Steps */}
              {structuredPlan.next_immediate_steps && Array.isArray(structuredPlan.next_immediate_steps) && (
                <div className="bg-purple-50/50 dark:bg-purple-950/20 rounded-lg p-6 border border-purple-200/50">
                  <h2 className="text-xl font-semibold text-purple-700 dark:text-purple-400 mb-4 flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-purple-500"></div>
                    Next Immediate Steps
                  </h2>
                  <ol className="space-y-2">
                    {structuredPlan.next_immediate_steps.map((step: string, index: number) => (
                      <li key={index} className="text-sm text-muted-foreground flex items-start gap-3">
                        <span className="bg-purple-500 text-white text-xs rounded-full w-5 h-5 flex items-center justify-center flex-shrink-0 mt-0.5">
                          {index + 1}
                        </span>
                        {step}
                      </li>
                    ))}
                  </ol>
                </div>
              )}
            </div>

            {/* Timeline and Investment */}
            {(structuredPlan.estimated_timeline || structuredPlan.investment_required) && (
              <div className="grid md:grid-cols-2 gap-6">
                {structuredPlan.estimated_timeline && (
                  <div className="bg-muted/30 rounded-lg p-6 border border-border">
                    <h2 className="text-xl font-semibold text-foreground mb-3 flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-primary"></div>
                      Timeline
                    </h2>
                    <p className="text-muted-foreground leading-relaxed">{structuredPlan.estimated_timeline}</p>
                  </div>
                )}

                {structuredPlan.investment_required && (
                  <div className="bg-muted/30 rounded-lg p-6 border border-border">
                    <h2 className="text-xl font-semibold text-foreground mb-3 flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-secondary"></div>
                      Investment Required
                    </h2>
                    <p className="text-muted-foreground leading-relaxed">{structuredPlan.investment_required}</p>
                  </div>
                )}
              </div>
            )}
          </div>
        ) : (
          // Fallback to markdown display for backward compatibility
          <div className="max-w-none font-display text-foreground leading-relaxed text-base space-y-4">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                h1: ({ children }) => (
                  <h1 className="font-display text-5xl font-black tracking-tight gradient-text-primary border-b border-primary/20 pb-6 mb-8 mt-10 leading-tight">
                    {children}
                  </h1>
                ),
                h2: ({ children }) => (
                  <h2 className="font-display text-3xl font-bold text-foreground mb-6 mt-10 tracking-tight leading-tight">
                    {children}
                  </h2>
                ),
                h3: ({ children }) => (
                  <h3 className="font-display text-2xl font-semibold text-foreground/95 mb-4 mt-8 tracking-tight leading-snug">
                    {children}
                  </h3>
                ),
                h4: ({ children }) => (
                  <h4 className="font-display text-xl font-semibold text-foreground mb-3 mt-6 tracking-tight leading-snug">
                    {children}
                  </h4>
                ),
                h5: ({ children }) => (
                  <h5 className="font-display text-lg font-semibold text-foreground/90 mb-3 mt-5 leading-snug">
                    {children}
                  </h5>
                ),
                h6: ({ children }) => (
                  <h6 className="font-display text-base font-semibold text-foreground/80 mb-2 mt-4 leading-snug">
                    {children}
                  </h6>
                ),
                p: ({ children }) => (
                  <p className="mb-4 leading-relaxed text-foreground/90 font-normal text-base">
                    {children}
                  </p>
                ),
                ul: ({ children }) => (
                  <ul className="list-disc marker:text-primary/70 pl-4 space-y-0 mb-3 text-foreground/90">
                    {children}
                  </ul>
                ),
                ol: ({ children }) => (
                  <ol className="list-decimal marker:text-primary/70 pl-4 space-y-0 mb-3 text-foreground/90">
                    {children}
                  </ol>
                ),
                li: ({ children }) => (
                  <li className="leading-normal pl-0 text-base mb-1">
                    {children}
                  </li>
                ),
                strong: ({ children }) => (
                  <strong className="font-semibold text-foreground font-display">
                    {children}
                  </strong>
                ),
                em: ({ children }) => (
                  <em className="italic font-medium text-foreground/85 font-display">
                    {children}
                  </em>
                ),
                code: ({ children }) => (
                  <code className="bg-muted/80 px-2 py-1 rounded-md text-sm font-mono border border-border/50">
                    {children}
                  </code>
                ),
                blockquote: ({ children }) => (
                  <blockquote className="border-l-2 border-border pl-4 italic text-foreground/80 my-4">
                    {children}
                  </blockquote>
                ),
              }}
            >
              {enhancedContent}
            </ReactMarkdown>
          </div>
        )}
      </CardContent>
    </Card>
  );
}