import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download, Edit, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

interface JumpPlanDisplayProps {
  planContent: string;
  onEdit: () => void;
  onDownload: () => void;
}

export default function JumpPlanDisplay({ planContent, onEdit, onDownload }: JumpPlanDisplayProps) {
  if (!planContent.trim()) {
    return null;
  }

  return (
    <Card className="w-full bg-gradient-to-br from-primary/5 to-primary/10 border-primary/20">
      <CardHeader className="pb-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-full bg-gradient-to-br from-primary/20 to-primary/10">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle className="text-xl">Your AI-Generated Jump Plan</CardTitle>
              <p className="text-sm text-muted-foreground mt-1">
                Your personalized transformation roadmap
              </p>
            </div>
          </div>
          <Badge variant="secondary" className="bg-primary/10 text-primary border-primary/20">
            Generated by AI
          </Badge>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onDownload}
            className="gap-2"
          >
            <Download className="h-4 w-4" />
            Download Plan
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onEdit}
            className="gap-2"
          >
            <Edit className="h-4 w-4" />
            Refine with Chat
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <div className="prose prose-lg max-w-none dark:prose-invert 
                        prose-headings:text-foreground prose-headings:font-semibold 
                        prose-h1:text-2xl prose-h1:mb-6 prose-h1:mt-8 prose-h1:border-b prose-h1:pb-2
                        prose-h2:text-xl prose-h2:mb-4 prose-h2:mt-6 
                        prose-h3:text-lg prose-h3:mb-3 prose-h3:mt-5
                        prose-p:mb-4 prose-p:leading-relaxed
                        prose-ul:mb-4 prose-ul:space-y-2
                        prose-li:mb-2
                        prose-strong:text-primary prose-strong:font-semibold
                        prose-code:bg-muted prose-code:px-1 prose-code:py-0.5 prose-code:rounded
                        space-y-4">
          <ReactMarkdown 
            remarkPlugins={[remarkGfm]}
            components={{
              h1: ({ children }) => <h1 className="text-2xl font-semibold text-foreground border-b pb-2 mb-6 mt-8">{children}</h1>,
              h2: ({ children }) => <h2 className="text-xl font-semibold text-foreground mb-4 mt-6">{children}</h2>,
              h3: ({ children }) => <h3 className="text-lg font-semibold text-foreground mb-3 mt-5">{children}</h3>,
              p: ({ children }) => <p className="mb-4 leading-relaxed text-foreground">{children}</p>,
              ul: ({ children }) => <ul className="mb-4 space-y-2 pl-6">{children}</ul>,
              ol: ({ children }) => <ol className="mb-4 space-y-2 pl-6">{children}</ol>,
              li: ({ children }) => <li className="mb-2 text-foreground">{children}</li>,
              strong: ({ children }) => <strong className="text-primary font-semibold">{children}</strong>,
              code: ({ children }) => <code className="bg-muted px-1 py-0.5 rounded text-sm">{children}</code>,
            }}
          >
            {planContent}
          </ReactMarkdown>
        </div>
      </CardContent>
    </Card>
  );
}