import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Download, Edit, Sparkles } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { formatAIText } from '@/utils/aiTextFormatter';
import ComprehensiveJumpDisplay from './ComprehensiveJumpDisplay';

interface JumpPlanDisplayProps {
  planContent: string;
  structuredPlan?: any; // Optional structured data for enhanced display
  onEdit: () => void;
  onDownload: () => void;
}

// Helper function to check if structured plan matches comprehensive format
function isComprehensiveStructure(plan: any): boolean {
  return plan && 
    typeof plan === 'object' && 
    plan.overview && 
    plan.analysis && 
    plan.action_plan && 
    Array.isArray(plan.action_plan?.phases);
}

export default function JumpPlanDisplay({ planContent, structuredPlan, onEdit, onDownload }: JumpPlanDisplayProps) {
  if (!planContent.trim()) {
    return null;
  }

  const tryParseJSON = (text: string): any | null => {
    try { return JSON.parse(text); } catch { /* ignore */ }
    const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/```$/i, '').trim();
    try { return JSON.parse(cleaned); } catch { return null; }
  };

  const effectivePlan = React.useMemo(() => structuredPlan || tryParseJSON(planContent), [structuredPlan, planContent]);
  const enhancedContent = React.useMemo(() => formatAIText(planContent), [planContent]);

  return (
    <Card className="w-full bg-card border-border">
      <CardHeader className="pb-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-full bg-gradient-to-br from-primary/20 to-primary/10">
              <Sparkles className="h-5 w-5 text-primary" />
            </div>
            <div>
              <CardTitle className="text-xl">Your AI-Generated Jump Plan</CardTitle>
              <p className="text-sm text-muted-foreground mt-1">
                Your personalized transformation roadmap
              </p>
            </div>
          </div>
          <Badge variant="secondary" className="bg-primary/10 text-primary border-primary/20">
            Generated by AI
          </Badge>
        </div>
        <div className="flex gap-2">
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onDownload}
            className="gap-2"
          >
            <Download className="h-4 w-4" />
            Download Plan
          </Button>
          <Button 
            variant="outline" 
            size="sm" 
            onClick={onEdit}
            className="gap-2"
          >
            <Edit className="h-4 w-4" />
            Refine with Chat
          </Button>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        {effectivePlan && isComprehensiveStructure(effectivePlan) ? (
          // Use the comprehensive display for the new structured format
          <ComprehensiveJumpDisplay 
            jump={effectivePlan} 
            onEdit={onEdit}
            onDownload={onDownload}
            className="border-0 shadow-none"
          />
        ) : effectivePlan ? (
          // Fallback for simpler structured plans (legacy format)
          <div className="p-6 space-y-6">
            {/* Title */}
            {effectivePlan.title && (
              <div className="text-center pb-6 border-b border-border">
                <h1 className="text-3xl font-bold gradient-text-primary mb-2">{effectivePlan.title}</h1>
              </div>
            )}

            {/* Executive Summary */}
            {effectivePlan.executive_summary && (
              <div className="bg-gradient-to-r from-primary/5 to-primary/10 rounded-lg p-6 border border-primary/20">
                <h2 className="text-xl font-semibold text-primary mb-3 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-primary"></div>
                  Executive Summary
                </h2>
                <p className="text-muted-foreground leading-relaxed">{effectivePlan.executive_summary}</p>
              </div>
            )}

            {/* Simple Phases Display */}
            {effectivePlan.phases && Array.isArray(effectivePlan.phases) && (
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-primary"></div>
                  The Jump Plan
                </h2>
                {effectivePlan.phases.map((phase: any, index: number) => (
                  <div key={index} className="bg-card rounded-lg border border-border p-6 shadow-lg">
                    <div className="flex items-start justify-between mb-4">
                      <h3 className="text-xl font-semibold text-primary">
                        Phase {phase.phase_number || index + 1}: {phase.title}
                      </h3>
                      {phase.timeline && (
                        <span className="text-sm bg-primary/10 text-primary px-3 py-1 rounded-full">
                          {phase.timeline}
                        </span>
                      )}
                    </div>
                    {phase.description && (
                      <p className="text-muted-foreground mb-4 leading-relaxed">{phase.description}</p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        ) : (
          // Fallback to markdown display for backward compatibility or when no structured data
          <div className="p-6 max-w-none font-display text-foreground leading-relaxed text-base space-y-4">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                h1: ({ children }) => (
                  <h1 className="font-display text-5xl font-black tracking-tight gradient-text-primary border-b border-primary/20 pb-6 mb-8 mt-10 leading-tight">
                    {children}
                  </h1>
                ),
                h2: ({ children }) => (
                  <h2 className="font-display text-3xl font-bold text-foreground mb-6 mt-10 tracking-tight leading-tight">
                    {children}
                  </h2>
                ),
                h3: ({ children }) => (
                  <h3 className="font-display text-2xl font-semibold text-foreground/95 mb-4 mt-8 tracking-tight leading-snug">
                    {children}
                  </h3>
                ),
                h4: ({ children }) => (
                  <h4 className="font-display text-xl font-semibold text-foreground mb-3 mt-6 tracking-tight leading-snug">
                    {children}
                  </h4>
                ),
                h5: ({ children }) => (
                  <h5 className="font-display text-lg font-semibold text-foreground/90 mb-3 mt-5 leading-snug">
                    {children}
                  </h5>
                ),
                h6: ({ children }) => (
                  <h6 className="font-display text-base font-semibold text-foreground/80 mb-2 mt-4 leading-snug">
                    {children}
                  </h6>
                ),
                p: ({ children }) => (
                  <p className="mb-4 leading-relaxed text-foreground/90 font-normal text-base">
                    {children}
                  </p>
                ),
                ul: ({ children }) => (
                  <ul className="list-disc marker:text-primary/70 pl-4 space-y-0 mb-3 text-foreground/90">
                    {children}
                  </ul>
                ),
                ol: ({ children }) => (
                  <ol className="list-decimal marker:text-primary/70 pl-4 space-y-0 mb-3 text-foreground/90">
                    {children}
                  </ol>
                ),
                li: ({ children }) => (
                  <li className="leading-normal pl-0 text-base mb-1">
                    {children}
                  </li>
                ),
                strong: ({ children }) => (
                  <strong className="font-semibold text-foreground font-display">
                    {children}
                  </strong>
                ),
                em: ({ children }) => (
                  <em className="italic font-medium text-foreground/85 font-display">
                    {children}
                  </em>
                ),
                code: ({ children }) => (
                  <code className="bg-muted/80 px-2 py-1 rounded-md text-sm font-mono border border-border/50">
                    {children}
                  </code>
                ),
                blockquote: ({ children }) => (
                  <blockquote className="border-l-2 border-border pl-4 italic text-foreground/80 my-4">
                    {children}
                  </blockquote>
                ),
              }}
            >
              {enhancedContent}
            </ReactMarkdown>
          </div>
        )}
      </CardContent>
    </Card>
  );
}